export const TOP_FILMS_IS_LOADING = 'TOP_FILMS_IS_LOADING'
export const FETCH_TOP_FILMS_ERROR = 'FETCH_TOP_FILMS_ERROR'
export const FETCH_TOP_FILMS_SUCCESSFULLY = 'FETCH_TOP_FILMS_SUCCESSFULLY'

export const HOME_GENRES_IS_LOADING = 'HOME_GENRES_IS_LOADING'
export const FETCH_HOME_GENRES_SUCCESSFULLY = 'HOME_GENRES_FETCH_SUCCESSFULLY'
export const FETCH_HOME_GENRES_ERROR = 'FETCH_HOME_GENRES_ERROR'
