export const LIKED_FILMS_IS_LOADING = 'LIKED_FILMS_IS_LOADING'
export const FETCH_LIKED_FILMS_ERROR = 'FETCH_LIKED_FILMS_ERROR'
export const FETCH_LIKED_FILMS_SUCCESSFULLY = 'FETCH_LIKED_FILMS_SUCCESSFULLY'

export const LIKE_FILM = 'LIKE_FILM'
export const LIKE_FILM_ERROR = 'LIKE_FILM_ERROR'

export const UNLIKE_FILM = 'UNLIKE_FILM'
export const UNLIKE_FILM_ERROR = 'UNLIKE_FILM_ERROR'