export const LIKED_FILMS_IS_LOADING = 'LIKED_FILMS_IS_LOADING'
export const FETCH_LIKED_FILMS_ERROR = 'FETCH_LIKED_FILMS_ERROR'
export const FETCH_LIKED_FILMS_SUCCESSFULLY = 'FETCH_LIKED_FILMS_SUCCESSFULLY'

export const LIKE_FILM = 'LIKED_FILMS_IS_LOADING'
export const LIKE_FILM_ERROR = 'FETCH_LIKED_FILMS_ERROR'