export const LIKED_FILMS_IS_LOADING = 'LIKED_FILMS_IS_LOADING'
export const FETCH_LIKED_FILMS_ERROR = 'FETCH_LIKED_FILMS_ERROR'
export const FETCH_LIKED_FILMS_SUCCESSFULLY = 'FETCH_LIKED_FILMS_SUCCESSFULLY'

export const LIKE_FILM = 'LIKE_FILM'
export const LIKE_FILM_ERROR = 'LIKE_FILM_ERROR'

export const UNLIKE_FILM = 'UNLIKE_FILM'
export const UNLIKE_FILM_ERROR = 'UNLIKE_FILM_ERROR'

export const FAVORITE_FILMS_IS_LOADING = 'FAVORITE_FILMS_IS_LOADING'
export const FETCH_FAVORITE_FILMS_ERROR = 'FETCH_FAVORITE_FILMS_ERROR'
export const FETCH_FAVORITE_FILMS_SUCCESSFULLY = 'FETCH_FAVORITE_FILMS_SUCCESSFULLY'

export const FAVORITE_FILM = 'FAVORITE_FILM'
export const FAVORITE_FILM_ERROR = 'FAVORITE_FILM_ERROR'

export const UNFAVORITE_FILM = 'UNFAVORITE_FILM'
export const UNFAVORITE_FILM_ERROR = 'UNFAVORITE_FILM_ERROR'